<a href="https://twitter.com/watakon_ten" target="_blank">わた婚展公式X</a>で公開された、「わた婚アニメにおける心ときめくシーンやセリフ」について、キャストの皆さまのコメントを一挙公開！<br>
<br>
<h2 class="detail_ttl">斎森美世役　上田麗奈</h2>
<p><img class="image" src="img/20231214/ueda.jpg" alt="斎森美世役　上田麗奈さんコメント"></p>
<br>
<br>
<h2 class="detail_ttl">久堂清霞役　石川界人</h2>
<p><img class="image" src="img/20231214/ishikawa.jpg" alt="久堂清霞役　石川界人さんコメント"></p>
<br>
<br>
<h2 class="detail_ttl">斎森香耶役　佐倉綾音</h2>
<p><img class="image" src="img/20231214/sakura.jpg" alt="斎森香耶役　佐倉綾音さんコメント"></p>
<br>
<br>
<h2 class="detail_ttl">辰石幸次役　西山宏太朗</h2>
<p><img class="image" src="img/20231214/nishiyama.jpg" alt="辰石幸次役　西山宏太朗さんコメント"></p>
<br>
<br>
<h2 class="detail_ttl">ゆり江役　桑島法子</h2>
<p><img class="image" src="img/20231214/kuwashima.jpg" alt="ゆり江役　桑島法子さんコメント"></p>
<br>
<br>
<h2 class="detail_ttl">五道佳斗役　下野紘</h2>
<p><img class="image" src="img/20231214/shimono.jpg" alt="五道佳斗役　下野紘さんコメント"></p>
<br>
<br>
<h2 class="detail_ttl">辰石一志役　深町寿成</h2>
<p><img class="image" src="img/20231214/fukamachi.jpg" alt="辰石一志役　深町寿成さんコメント"></p>
<br>
<br>
<h2 class="detail_ttl">薄刃新役　木村良平</h2>
<p><img class="image" src="img/20231214/kimura.jpg" alt="薄刃新役　木村良平さんコメント"></p>
<br>
<br>

展示会では、わた婚アニメの制作陣の「ときめく」シーンの掲載やコメントが展示されます。<br>
どうぞお楽しみに♪