本企画展の描き下ろしキービジュアルを初公開！<br>
美世と清霞にスポットをあてた本展のために描き下ろされたビジュアルでは、花びらが舞い散るしだれ桜の下、互いに寄り添い合う美世と清霞が描かれています。<br>
<br>
<p class="image1"><img src="img/20231205/1.jpg" style="width: 100%;"></p>

<style type="text/css" media="screen">
	.image1 {
		width: 100%;
		margin: 0 auto !important;
	}
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 40/375) !important;
	}
   
   @media screen and (min-width: 960px) {
		.image1 {
			width: 50%;
		}
		.page_wrap.wrap_contents .contents_box {
		   padding-top: 54px !important;
		}
	}
</style>