限定グッズ付き入場券の本展描き下ろしキービジュアルを使用した「万年カレンダー」を公開！<br>
チケット情報については<a href="/ticket/">チケットページ</a>を要チェック🌸
<br>
<br>
<p class="image1"><img src="img/20231205/3.jpg" style="width: 100%;"></p>

<style type="text/css" media="screen">
	.image1 {
		width: 100%;
		margin: 0 auto !important;
	}
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 40/375) !important;
	}
   
   @media screen and (min-width: 960px) {
		.image1 {
			width: 50%;
		}
		.page_wrap.wrap_contents .contents_box {
		   padding-top: 54px !important;
		}
	}
</style>