企画展にご来場いただいた方に、展示会場入り口にて入場者特典カード（全３種）をランダムで１枚プレゼント！<br>
また、期間中“着物”でお越しの方には３種すべてをプレゼントします♪ぜひ着物でご来場ください。<br><br>
<p class="tokuten_pic">
	<img class="image" src="img/20231227/tokuten_card.png">
</p>
<br>
<ul class="memo">
	<li>特典はなくなり次第終了となります。</li>
	<li>特典の絵柄はお選びいただけません。</li>
	<li>画像はイメージです。実際とは異なる場合がございます。</li>
</ul>

<style type="text/css" media="screen">
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 24/375);
	}
	@media screen and (min-width: 960px) {
		.page_wrap.wrap_contents .contents_box {
			padding-top: 50px !important;
		}
	}
</style>