斎森美世役・上田麗奈さん、久堂清霞役・石川界人さんの特別コメント動画が到着！<br>
ぜひチェックしてみてください！<br>
<br>
<div class="youtube">
	<iframe width="560" height="315" src="https://www.youtube.com/embed/gYfwucqqoxI?si=ZllQ-rqNQ9qie90A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>

<style type="text/css" media="screen">
	.image1 {
		width: 100%;
		margin: 0 auto !important;
	}
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 40/375) !important;
	}
   
   @media screen and (min-width: 960px) {
		.image1 {
			width: 70%;
		}
		.page_wrap.wrap_contents .contents_box {
		   padding-top: 54px !important;
		}
	}
</style>