テレビアニメ「わたしの幸せな結婚」展の開催を記念して、松屋銀座8F MGカフェでのコラボカフェ開催が決定！<br>
メニューやノベルティの詳細は後日発表いたしますのでどうぞお楽しみに♪
<br>
<table class="schedule">
	<tbody>
		<tr>
			<th class="ttl">期間</th>
			<td>2024年1月5日（金）－23日（火）</td>
		</tr>
		<tr>
			<th class="ttl">営業時間</th>
			<td>
				午前11時－午後10時（ラストオーダー 午後9時）<br>
				1月8日（月）、14日（日）、21日（日）は午後9時30分閉店（ラストオーダー　午後8時30分）
			</td>
		</tr>
		<tr>
			<th class="ttl">場所</th>
			<td>8階MGカフェ</td>
		</tr>
		<tr>
			<th class="ttl">店舗詳細</th>
			<td><a href="https://www.matsuya.com/ginza/restaurant/mg-cafe/" target="_blank">https://www.matsuya.com/ginza/restaurant/mg-cafe/</a></td>
		</tr>
		<tr>
			<th class="ttl">公式X</th>
			<td><a href="https://twitter.com/mgcafe_sob" target="_blank">@mgcafe_sob</a></td>
		</tr>
	</tbody>
</table>

