テレビアニメ「わたしの幸せな結婚」展の開催を記念した、松屋銀座８F MGカフェでのコラボカフェの詳細が到着！<br>
メニューやノベルティをご紹介♪会場にお越しの際はぜひお立ち寄りください！<br>
<table class="schedule">
	<tbody>
		<tr>
			<th class="ttl">期間</th>
			<td>2024年1月5日（金）－23日（火）</td>
		</tr>
		<tr>
			<th class="ttl">営業時間</th>
			<td>
				午前11時－午後10時（ラストオーダー 午後9時）<br>
				1月8日（月）、14日（日）、21日（日）は午後9時30分閉店（ラストオーダー　午後8時30分）
			</td>
		</tr>
		<tr>
			<th class="ttl">場所</th>
			<td>8階MGカフェ</td>
		</tr>
		<tr>
			<th class="ttl">店舗詳細</th>
			<td><a href="https://www.matsuya.com/ginza/restaurant/mg-cafe/" target="_blank">https://www.matsuya.com/ginza/restaurant/mg-cafe/</a></td>
		</tr>
		<tr>
			<th class="ttl">公式X</th>
			<td><a href="https://twitter.com/mgcafe_sob" target="_blank">@mgcafe_sob</a></td>
		</tr>
	</tbody>
</table>

<p class="collabo_ttl">《コラボメニュー》</p>
<h2 class="detail_ttl">ドリンク</h2>
<div class="menu flex">
	<div class="box cafe_txt">
		<dl>
			<dt class="menu_name"><span>「わたしの幸せな結婚」幸せラテ　990円(税込)</span></dt>
			<dd>
				キャラクターをプリントしたランダムラテ。
			</dd>
			<dd class="memo">
				※テイクアウトOK<br>
				※絵柄はランダムとなります。（全４種類）
			</dd>
		</dl>
	</div>
	<div class="box cafe_menu">
		<img class="image" src="img/20231227/cafe1.jpg">
	</div>
</div>
<div class="menu flex bdr_none">
	<div class="box cafe_txt">
		<dl>
			<dt class="menu_name"><span>「わたしの幸せな結婚」幸せ桜ソーダ　1,210円(税込)</span></dt>
			<dd>
				桜味のソーダにアイスクリームを浮かべました。
			</dd>
			<dd class="memo">
				※テイクアウトOK
			</dd>
		</dl>
	</div>
	<div class="box cafe_menu collabo_pic_vertical">
		<img class="image" src="img/20231227/cafe2.jpg">
	</div>
</div>

<h2 class="detail_ttl">デザート</h2>
<div class="menu flex">
	<div class="box cafe_txt">
		<dl>
			<dt class="menu_name"><span>「出会い」デザートプレート　1,540円(税込)</span></dt>
			<dd>ベリーとピスタチオのムース、抹茶アイス、三色団子に美世と清霞の瞳のようなゼリーを添えました。ランダムフラッグ付。</dd>
		</dl>
	</div>
	<div class="box cafe_menu">
		<img class="image" src="img/20231227/cafe3.jpg">
	</div>
</div>
<div class="menu flex bdr_none">
	<div class="box cafe_txt">
		<dl>
			<dt class="menu_name"><span>「暗闇の中の光」パフェ　1,540円(税込)</span></dt>
			<dd>チョコプリンとイチゴのパフェにブラウニー、巻きチョコを飾りました。ランダムフラッグ付。</dd>
		</dl>
	</div>
	<div class="box cafe_menu collabo_pic_vertical">
		<img class="image" src="img/20231227/cafe4.jpg">
	</div>
</div>

<h2 class="detail_ttl">フード</h2>
<div class="menu flex">
	<div class="box cafe_txt">
		<dl>
			<dt class="menu_name"><span>贈り物サンドイッチ　1,650円(税込)</span></dt>
			<dd>清霞が美世に贈った「櫛」をイメージしたサンドイッチには、桜の形のハムとマヨネーズを添えました。ランダムフラッグ付。</dd>
		</dl>
	</div>
	<div class="box cafe_menu">
		<img class="image" src="img/20231227/cafe5.jpg">
	</div>
</div>
<div class="menu flex bdr_none">
	<div class="box cafe_txt">
		<dl>
			<dt class="menu_name"><span>贈り物クリームパスタ　1,650円(税込)</span></dt>
			<dd>クリームパスタに美世が清霞に贈った「組み紐」をイメージした紫キャベツと錦糸卵を飾りました。ランダムフラッグ付。</dd>
		</dl>
	</div>
	<div class="box cafe_menu">
		<img class="image" src="img/20231227/cafe6.jpg">
	</div>
</div>

<p class="collabo_ttl" style="margin-bottom: 1em !important;">《ノベルティ》</p>
<div class="menu flex bdr_none mgn_pad_none">
	<div class="box cafe_txt">
		<dl>
			<dt class="menu_name"><span>特典コースター（全４種）</span></dt>
			<dd>コラボメニューを一品ご注文ごとに、特典コースター（全４種）をランダムで１枚、メニューのご提供と一緒にお渡しいたします。</dd>
			<dd class="memo">
				※画像はイメージです。<br>
				※コラボメニューを一品ご注文ごとに、特典コースター（全４種）をランダムで１枚、メニューのご提供と一緒にお渡しいたします。<br>
				※特典の数には限りがあり、なくなり次第終了とさせていただきます。<br>
				※特典の絵柄はお選びいただけません。
			</dd>
		</dl>
	</div>
	<div class="box cafe_menu">
		<img class="image" src="img/20231227/cafe_toluten.png">
	</div>
</div>

<style type="text/css" media="screen">
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 24/375);
	}
	#news dd.memo {
		margin: 1em 0 !important;
	}
	
	@media screen and (min-width: 960px) {
		.page_wrap.wrap_contents .contents_box {
			padding-top: 50px !important;
		}
		.flex {
			justify-content: space-between;
		}
		.flex .box  {
			width: 48%;
		}
		
	}
</style>