11/12(日)にてYouTube生配信が決定した「TVアニメ「わたしの幸せな結婚」《いい夫婦の日》スペシャル特番」内にて、本企画展 の最新情報をご紹介します&#127800;<br>
企画展の中身や気になるオリジナルグッズなど、様々な情報をお届け予定です。<br>
どうぞお楽しみに✨<br>
<br>
<h2 class="detail_ttl">配信詳細</h2>
&#127800;配信URL&#127800;<br>
<span class="link"><a href="https://www.youtube.com/watch?v=EGw9yiRf8BM" target="_blank">KADOKAWA AnimeChannnel</a></span>　　にて生配信<br>
<br>
<div class="youtube">
	<iframe width="560" height="315" src="https://www.youtube.com/embed/EGw9yiRf8BM?si=qMXhAQOGidVqwE6T" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
<br>
&#127800;配信日時&#127800;<br>
11月12日(日)<br>
<br>
&#127800;出演者&#127800;<br>
上田麗奈（斎森美世役）<br>
石川界人（久堂清霞役）