4月13日(土)より大阪、6月13日(木)より福岡にて、本企画展の巡回が決定しました。<br>
巡回展では、追加のオリジナルグッズも販売予定！<br>
<br>
≪大阪会場≫ <br>
■会期：2024年４月１３日(土)～５月６日(月)<br>
 <br>
≪福岡会場≫ <br>
■会期：2024年６月１３日(木)～７月１日(月) <br>
 <br>
ほか会場については、詳細が決まり次第お知らせいたします。<br>
また、開催会場、チケット販売情報、後日公式HPおよび公式Xにてお知らせいたします。<br>
どうぞお楽しみに！<br>
<br>
■イベント公式ホームページ：<a href="https://watakon-ten.com">https://watakon-ten.com</a><br>       
■イベント公式X（旧Twitter）アカウント：<a href="https://twitter.com/watakon_ten" target="_blank">＠watakon_ten</a><br>
<br>

<p class="image1"><img src="img/20240123/1.png" style="width: 100%;"></p>
<br>
※本企画展に関する情報は予告なく変更になる場合がございます。<br>
※本企画展はやむを得ない事情により開催期間が変更、中止、延期となる場合がございます。　<br>
最新情報、詳細、注意事項を企画展公式サイトにて必ずご確認のうえご来場ください。


<style type="text/css" media="screen">
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 24/375);
	}
	
	@media screen and (min-width: 960px) {
		.page_wrap.wrap_contents .contents_box {
			padding-top: 50px !important;
		}
		
	}
</style>	