<p><img src="img/20240104/kimono.png" style="width: 100%;"></p>
<br>
1/5～1/23の会期中、着物でご来場くださった方には入場特典（全３種・ランダム配布）を特別に"３種全て"プレゼント！<br>
着物を持っていない方は、松屋銀座から徒歩３分にある、「着物レンタルVASARA銀座三丁目店」をぜひご利用くださいませ。<br>
<br>
予約ページはこちら ⇒<br>
<a href="https://vasara-h.co.jp/shop/detail.html?id=4" target="_blank">https://vasara-h.co.jp/shop/detail.html?id=4</a><br>
<br>
<ul class="memo">
	<li>特典はなくなり次第終了となります。</li>
	<li>画像はイメージです。実際とは異なる場合がございます。</li>
</ul>

<style type="text/css" media="screen">
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 24/375);
	}
	#news dd.memo {
		margin: 1em 0 !important;
	}
	
	@media screen and (min-width: 960px) {
		.page_wrap.wrap_contents .contents_box {
			padding-top: 50px !important;
		}
		.flex {
			justify-content: space-between;
		}
		.flex .box  {
			width: 48%;
		}
		
	}
</style>	