斎森美世役・上田麗奈さんに会場にお越しいただき、レポートしていただきました！<br>
企画展オリジナル録り下ろしボイスや、久堂清霞の書斎再現、サラウンド音声体験などなど、わた婚アニメの魅力を体感できる展示を、心ゆくまでご堪能いただきました。
皆さまもぜひぜひお越しください♪<br>
<br>
衣装協力：着物レンタルVASARA銀座三丁目店<br>
<br>

<div class="youtube">
	<iframe width="560" height="315" src="https://www.youtube.com/embed/eDitpOGJ6-0?si=5ihWcQp8_W24NRQL" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</div>
