企画展にご来場いただいた方に、展示会場入り口にて特製ステッカー（全６種）をランダムで１枚プレゼント！<br>
会期の前半と後半で絵柄が異なります。<br>
<br>
<h2 class="detail_ttl">4/13（土）～24（水）：美世、清霞、香耶、幸次</h2>
<p class="image1"><img src="../ticket/img/sticker1.jpg" style="width: 100%;"></p>
<br>
<h2 class="detail_ttl">4/25（木）～5/6（月）：美世、清霞、五道、新</h2>
<p class="image1"><img src="../ticket/img/sticker2.jpg" style="width: 100%;"></p>
<br>
※特典はなくなり次第終了となります。<br>
※特典の絵柄はお選びいただけません。<br>
※画像はイメージです。実際とは異なる場合がございます。

<style type="text/css" media="screen">
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 24/375);
	}
	
	@media screen and (min-width: 960px) {
		.page_wrap.wrap_contents .contents_box {
			padding-top: 50px !important;
		}
		
	}
</style>	