本日12時より「わたしの幸せな結婚」大阪巡回展のチケットの販売が開始しました！<br>
下記リンクよりお求めいただけます🌸<br>
<a href="https://l-tike.com/watakon_ten/" target="_blank">https://l-tike.com/watakon_ten/</a><br>
<br>
限定グッズ付入場券やペアチケットの販売もございます👀<br>
お見逃しなく✨<br>
<br>
<p class="image1"><img src="img/20240301/1.png" style="width: 100%;"></p>

<!--
<style type="text/css" media="screen">
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 24/375);
	}
	
	@media screen and (min-width: 960px) {
		.page_wrap.wrap_contents .contents_box {
			padding-top: 50px !important;
		}
		
	}
</style>	
-->