<p><img src="img/20240105/comment.jpg" style="width: 100%;"></p>
<br>
本日から始まるテレビアニメ「わたしの幸せな結婚」展の開催を記念して、原作者の顎木あくみ先生からコメントをいただきました！<br>
会場には先生のサイン色紙も展示されています。ぜひチェックしてくださいね♪

<style type="text/css" media="screen">
	.page_wrap.wrap_contents .contents_box {
		padding-top: calc(100vw * 24/375);
	}
	#news dd.memo {
		margin: 1em 0 !important;
	}
	
	@media screen and (min-width: 960px) {
		.page_wrap.wrap_contents .contents_box {
			padding-top: 50px !important;
		}
		.flex {
			justify-content: space-between;
		}
		.flex .box  {
			width: 48%;
		}
		
	}
</style>	