<?php

$title = "$page_ttl | ";
$page = "outline";
require_once("../common.php");
include_once("{$settings['docroot']}/inc/meta.inc");
include_once("{$settings['docroot']}/inc/header.inc");

?>

<div id="<?php echo $page?>" class="page_wrap wrap_contents">
	<?php include_once("../inc/sakura.inc"); ?>
	<div class="wrap_contents_inner">
		<div class="page_ttl page">
         <div class="wrap_page_ttl">
            <h1>
				   <p><img class="image" src="../img/common/musubi_purple.png"></p>
				   <?php echo $page_ttl?>
				</h1>
         </div>
      </div>
      
      <div class="primary">
	      <div class="page_character lh-none">
				<img class="image" src="<?php echo $settings['rootdir']?>/img/common/mini_miyo2.png">
			</div>
			<div class="frame">
				<h2 class="around">大阪会場</h2>
			   <div class="contents_box">
				   <div class="text">
					   <div class="table_layout">
						   <dl class="dl_tbl">
					         <?php /*?><dt>企画展名</dt>
					         <dd>
					            テレビアニメ「わたしの幸せな結婚」展
					         </dd><?php */?>
					         <dt>会期</dt>
					         <dd>2024年4月13日(土)～5月6日(月・祝)</dd>
					         <dt>時間</dt>
					         <dd>
					            11:00～21:00（入場は閉場の30分前まで）
					            <ul class="memo">
						            <li>最終日は18：00閉場</li>
						            <li>混雑状況によって整理券の配布、もしくはお待ちいただく場合がございます。</li>
					            </ul>
					            <ul>
						            <li>住所：〒530-0013大阪府大阪市北区茶屋町16-7</li>
						            <li>交通：阪急京都本線・阪急神戸本線・阪急宝塚本線「大阪梅田駅」茶屋町口より徒歩5分<br>
						            大阪メトロ御堂筋線「中津駅」より徒歩7分</li>
					            </ul>
					            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3279.889073800906!2d135.49735657600195!3d34.70797767291707!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6000e6911d118331%3A0xbd368261e56a9c68!2z44CSNTMwLTAwMTMg5aSn6Ziq5bqc5aSn6Ziq5biC5YyX5Yy66Iy25bGL55S677yR77yW4oiS77yX!5e0!3m2!1sja!2sjp!4v1708057667045!5m2!1sja!2sjp" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
					         </dd>
					         <dt>会場</dt>
					         <dd>梅田ロフト4階イベントスペース</dd>
					         <dt>お問合わせ先</dt>
					         <dd>06-6359-0111（代表）</dd>
					         <dt>会場ホームページ</dt>
					         <dd class="link"><a href="https://www.loft.co.jp/shop_list/info.php?shop_id=143&info_id=509211" target="_blank">https://www.loft.co.jp/shop_list/info.php?shop_id=143&info_id=509211</a></dd>
					         <dt>主催</dt>
					         <dd>梅田ロフト</dd>
					         <dt>企画</dt>
					         <dd>テレビアニメ「わたしの幸せな結婚」展実行委員会</dd>
					         <dt>協力</dt>
					         <dd>「わたしの幸せな結婚」製作委員会</dd>
						   </dl>
						</div>
				   </div>
			   </div>
			</div>
	   </div>
	   
	   <div class="primary">
			<div class="frame">
				<h2 class="around">福岡会場</h2>
			   <div class="contents_box">
				   <div class="text">
					   <div class="table_layout">
						   <dl class="dl_tbl">
					         <?php /*?><dt>企画展名</dt>
					         <dd>
					            テレビアニメ「わたしの幸せな結婚」展
					         </dd><?php */?>
					         <dt>会期</dt>
					         <dd>2024年6月13日(木)～7月1日(月)</dd>
					         <dt>時間</dt>
					         <dd>
					         	午前10時～午後8時（入場は閉場の1時間前まで）
					         	<ul class="memo">
						         	<li>営業時間は変更となる場合がございます。詳しくは博多阪急ホームページをご覧ください。</li>
						         	<li>最終日は午後5時閉場</li>
						         	<li>混雑状況によって整理券の配布、もしくはお待ちいただく場合がございます。</li>
					         	</ul>
					         	<ul class="memo icon_none">
						         	<li>住所：〒812-0012 福岡市博多区博多駅中央街1番1号</li> 
						         	<li>交通：JR・福岡市営地下鉄「博多」駅からすぐ</li> 
					         	</ul>		
					         	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3323.6142348317603!2d130.41726287595742!3d33.58936397333482!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x354191c7ea885905%3A0xca47a6716a9884ec!2z5Y2a5aSa6Ziq5oCl!5e0!3m2!1sja!2sjp!4v1708393474861!5m2!1sja!2sjp" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>			         	
								</dd>
								<dt>会場</dt>
					         <dd>博多阪急　 8階 催場</dd>
					         <dt>お問合わせ先</dt>
					         <dd>092-461-1381（代表）</dd>
					         <dt>会場ホームページ</dt>
					         <dd class="link"><a href="https://www.hankyu-dept.co.jp/hakata/event/" target="_blank">https://www.hankyu-dept.co.jp/hakata/event/</a></dd>
					         <dt>主催</dt>
					         <dd>博多阪急</dd>
					         <dt>企画</dt>
					         <dd>テレビアニメ「わたしの幸せな結婚」展実行委員会</dd>
					         <dt>協力</dt>
					         <dd>「わたしの幸せな結婚」製作委員会</dd>
						   </dl>
						</div>
				   </div>
			   </div>
			</div>
	   </div>
		
		<div class="primary">
			<div class="frame">
				<h2>東京会場</h2>
			   <div class="contents_box">
				   <div class="text">
					   <div class="table_layout">
						   <dl class="dl_tbl">
					         <dt>企画展名</dt>
					         <dd>
					            テレビアニメ「わたしの幸せな結婚」展
					         </dd>
					         <dt>会期</dt>
					         <dd>
					            2024年1月5日(金)～1月23日(火)
					         </dd>
					         <dt>時間</dt>
					         <dd>
					            11:00～20:00（入場は閉場の30分前まで）
					            <ul class="memo">
						            <li>1月8日（祝・月）、1月14日（日）、1月21日（日）は19:30閉場</li>
						            <li>最終日は17：00閉場</li>
						            <li>初日・1月5日（金）の11時～13時のみ日時指定券が必要となります。</li>
						            <li>「各種松屋カード（ポイントカードを除く）」「障がい者手帳」「招待券」をお持ちのお客様は、1月5日（金）13時以降のご入場が可能です。</li>
						            <li>混雑状況によって整理券の配布、もしくはお待ちいただく場合がございます。</li>
					            </ul>
					         </dd>
					         <dt>会場</dt>
					         <dd>
					            松屋銀座8階イベントスクエア
					            <ul class="memo icon_none">
						            <li>住所：〒101‐8130 東京都中央区銀座3-6-1</li>
						            <li>交通：東京メトロ銀座線、丸ノ内線、日比谷線「銀座駅」A12番出口直結</li>
					            </ul>
					            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3241.198045594116!2d139.7638116759218!3d35.67212523047387!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x60188b2f73e887b7%3A0x25f5871572182166!2z44CSMTA0LTAwNjEg5p2x5Lqs6YO95Lit5aSu5Yy66YqA5bqn77yT5LiB55uu77yW4oiS77yR!5e0!3m2!1sja!2sjp!4v1697966583170!5m2!1sja!2sjp" width="400" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
					         </dd>
					         <dt>お問合わせ先</dt>
					         <dd>
					         	<div class="link">
					         		<a href="https://www.matsuya.com/ginza/" target="_blank" rel="noopener noreferrer nofollow">松屋銀座</a>
					         	</div>
					         </dd>
					         <dt>イベント公式X（旧Twitter）<br class="pc">アカウント</dt>
					         <dd>
					         	<div class="link">
						         	<a href="http://twitter.com/<?php echo $settings['twitter_id']?>" target="_blank" rel="noopener noreferrer nofollow">＠watakon_ten</a>
						         </div>
						         ハッシュタグ：#わた婚展
					         </dd>
					         <dt>主催</dt>
					         <dd>テレビアニメ「わたしの幸せな結婚」展実行委員会</dd>
					         <dt>協力</dt>
					         <dd>「わたしの幸せな結婚」製作委員会</dd>
					         <dt>宣伝協力</dt>
					         <dd>TOKYO MX</dd>
					      </dl>
						   <ul class="memo">
							   <li>本企画展は、予告なしで展示内容が変更・中止になる可能性がございます。</li>
							</ul>
						   
						</div>
				   </div>
			   </div>
			</div>
	   </div>
		
	</div><?php /*?>page_wrap wrap_contents<?php */?>
</div><?php /*?>wrap_contents_inner<?php */?>



<?php include_once("{$settings['docroot']}/inc/footer.inc"); ?>

