<?php
$title = "$page_ttl | ";
$page = "ticket";
require_once("../common.php");
include_once("{$settings['docroot']}/inc/meta.inc");
include_once("{$settings['docroot']}/inc/header.inc");

?>

<div id="<?php echo $page?>" class="page_wrap wrap_contents">
	<?php include_once("../inc/sakura.inc"); ?>
	<div class="wrap_contents_inner">
		<div class="page_ttl page">
         <div class="wrap_page_ttl">
            <h1>
				   <p><img class="image" src="../img/common/musubi_purple.png"></p>
				   <?php echo $page_ttl?>
				</h1>
         </div>
      </div>
      
      <div class="primary">
			<ul class="tab-list">
			  <li class="tab-list-item active">東京会場<span class="memo">(開催終了)</span></li>
			  <li class="tab-list-item">大阪会場</li>
			  <li class="tab-list-item">福岡会場</li>
			</ul>
			
			<div class="tab-contents">
				<div class="tab-contents-item show">
					<div class="primary">
						<div class="page_character lh-none">
							<img class="image" src="<?php echo $settings['rootdir']?>/img/common/mini_kiyoka2.png">
						</div>
						<div class="frame">
							<h2><p class="memo">東京会場は開催終了いたしました</p>ご購入について</h2>
						   <div class="contents_box">
							   <div class="text">
								   <div class="table_layout">
									   <dl class="dl_tbl dl_tbl_large">
								         <dt>チケットの種類と料金</dt>
								         <dd>
								            本企画展へのご入場には「日時指定券」「限定グッズ付き日時指定券」「入場券（日時指定なし）」「限定グッズ付き入場券」「各種松屋カード（ポイントカードを除く）」「障がい者手帳」「招待券」のいずれかが必要です。<br>
								         	<table>
													<tbody>
														<tr>
															<td class="heading"></td>
															<td class="heading">入場対象期間</td>
															<td class="heading">一般</td>
															<td class="heading">高校生</td>
															<td class="heading">中学生</td>
															<td class="heading">小学生</td>
															<td class="heading">限定グッズ付き<br>（一般のみ）</td>
														</tr>
														<tr>
															<td class="heading">日時指定券</td>
															<td>
																2024年<br>
																1月5日（金）<br>
																11:00～13:00
															</td>
															<td rowspan="2" class="price">1,300<br class="sp">円</td>
															<td rowspan="2" class="price">700<br class="sp">円</td>
															<td rowspan="2" class="price">500<br class="sp">円</td>
															<td rowspan="2" class="price">400<br class="sp">円</td>
															<td rowspan="2" class="price">3,000<br class="sp">円</td>
														</tr>
														<tr>
															<td class="heading">入場券<br>（日時指定なし）</td>
															<td>
																2024年<br>
																1月5日（金）<br>
																13:00以降の<br>
																会期中
															</td>
														</tr>
													</tbody>
												</table>
												<div class="gray_bg">
													<ul class="memo">
														<li>料金はすべて税込み表記となります。</li>
														<li>前売券および日時指定券の販売は、ローソンチケットのみでの取り扱いとなります。</li>
														<li>会期中は松屋銀座8階イベントスクエアでも入場券の販売をいたします。前売券料金と当日券料金は同額です。</li>
													</ul>
												</div>
								         </dd>
								         
								         <dt>チケット販売スケジュール</dt>
								         <dd>
								        		<div class="wrap_ticket">
									         	<p class="ticket_type"><span>日時指定券/限定グッズ付き日時指定券</span></p>
									         	
									         	<table class="ticket_schedule">
														<tbody>
															<tr>
																<th class="ttl">抽選販売受付</th>
																<td>2023年11月10日（金）12:00〜11月19日（日）23:59</td>
															</tr>
															<tr>
																<th class="ttl">当選発表</th>
																<td>
																	2023年11月22日（水）12:00～（引き取り期限：11月24日（金）23:59まで）
																	<p class="memo">※抽選後、日時指定枠に空枠があった場合には、一般販売（※先着順）をいたします。</p>
																</td>
															</tr>
														</tbody>
													</table>
									         	
												</div>
												
												<div class="wrap_ticket mb0">
													<p class="ticket_type"><span>入場券（日時指定なし）/限定グッズ付き入場券</span></p>
													<table class="ticket_schedule">
														<tbody>
															<tr>
																<th class="ttl">販売開始</th>
																<td>2023年11月10日（金）12：00～</td>
															</tr>
														</tbody>
													</table>
												</div>
			
										      <div class="btns">
											      <a  class="btn" href="https://l-tike.com/watakon_ten/" target="_blank" rel="noopener noreferrer">購入はこちらから</a>
										      </div>
								         </dd>
								         
								         <dt>チケット販売方法</dt>
								         <dd class="border_btn_none">
								         	<div class="wrap_ticket">
									         	<p class="ticket_type"><span>前売券および日時指定券の販売</span></p>
									         	<div class="group">
										         	<div class="link">
										         		・<a href="https://l-tike.com/watakon_ten/" target="_blank" rel="noopener noreferrer nofollow">インターネット予約</a>
										         	</div>
										         	・全国ローソン・ミニストップ設置のＬｏｐｐｉ　ローソンチケット（Ｌコード30211）
									         	</div>
								         	</div>
								         	<div class="wrap_ticket mb_0">
									         	<p class="ticket_type"><span>チケットに関するお問い合わせ</span></p>
									         	<div class="group">
										         	<div class="link">
										         		・<a href="https://l-tike.com/contact/" target="_blank" rel="noopener noreferrer nofollow">ローソンチケット</a>
										         	</div>
									         	</div>
									         	<div class="gray_bg">
														<ul class="memo">
															<li class="bold">前売券および日時指定券の販売は、ローソンチケットのみでの取り扱いとなります。</li>
															<li>ローソンチケットでのインターネット予約のご利用にはチケット代の他に手数料が必要です。</li>
															<li>会期中は松屋銀座8階イベントスクエアでも入場券の販売をいたします。</li>
														</ul>
													</div>
								         	</div>
								         </dd>
								      </dl>
									</div>
							   </div>
						   </div>
						</div>
						<div class="frame guide">
							<h2>ご案内</h2>
						   <div class="contents_box">
							   <div class="text">
								   <div class="table_layout">
									   <dl class="dl_tbl dl_tbl_large">
								         <dt>日時指定券の販売について</dt>
								         <dd>
								            <b>本企画展の入場は初日・2024年1月5日（金）11: 00～13:00のみ日時指定制となります。</b><br>
												この時間帯については日時指定券をご購入ください。なお、初日13:00以降と、2日目以降は日時指定をお取りいただく必要はありません。<br>
												日時指定券の販売は、抽選とさせていただきます。
												
												<div class="gray_bg">
													<ul class="memo">
														<li>「日時指定券」の当選発表の日時は、2023年11月22日（水）12：00を予定しております。</li>
														<li>抽選後、日時指定枠に空枠があった場合には、一般販売（※先着順）をいたします。</li>
														<li>前売券および日時指定券の販売は、ローソンチケットのみでの取り扱いとなります。</li>
													</ul>
												</div>
												<br>
											   <div class="wrap_ticket">
									         	<p class="ticket_type"><span>日時指定券　料金</span></p>
									         	<div class="group">
										         	<table class="mb0" style="width: 100%;">
															<tbody>
																<tr>
																	<td class="heading">一般</td>
																	<td class="heading">高校生</td>
																	<td class="heading">中学生</td>
																	<td class="heading">小学生</td>
																	<td class="heading">限定グッズ付き<br>（一般のみ）</td>
																</tr>
																<tr>
																	<td rowspan="2" class="price">1,300<br class="sp">円</td>
																	<td rowspan="2" class="price">700<br class="sp">円</td>
																	<td rowspan="2" class="price">500<br class="sp">円</td>
																	<td rowspan="2" class="price">400<br class="sp">円</td>
																	<td rowspan="2" class="price">3,000<br class="sp">円</td>
																</tr>
															</tbody>
														</table>
									         	</div>
								         	</div>
								         	<div class="wrap_ticket">
									         	<p class="ticket_type"><span>日時指定券　入場時間帯</span></p>
									         	<div class="group">
										         	2024年1月5日（金）11:00～13:00
														<ul class="memo">
															<li>購入時に入場時間帯の指定が必要です。</li>
														</ul>
														①11:00～／②12:00～
														<div class="gray_bg">
															<ul class="memo">
																<li>料金はすべて税込み表記となります。</li>
																<li>13:00以降はフリー入場となります。</li>
																<li>各時間帯数量限定となります。</li>
																<li>整理券番号順での入場となります。「日時指定券」に「整理番号」が記載されております。</li>
																<li>上記時間は入場案内開始時間ですので、入場券に記載された整理番号により「11:00～12:00」の入場時間帯を購入された場合でも、実際の入場時間が11:00以降となる場合がございます。事前に入場券を発行いただき、ご集合時間のご確認をお願いいたします。集合時間より前にご入場することはできません。</li>
																<li>未就学児は入場無料。ご入場の際は必ず保護者（18歳以上）同伴でご入場ください。保護者1名につき2名までご入場いただけます。</li>
																<li>未就学児は日時指定券不要ですが、同伴の保護者の方は日時指定券が必要となります。</li>
																<li>グッズコーナーのみのご入場は不可とさせていただきます。</li>
															</ul>
														</div>
									         	</div>
								         	</div>
								         </dd>
								         
								         <dt>入場者特典について</dt>
								         <dd>
									         企画展にご来場いただいた方に、展示会場入り口にて入場者特典カード（全３種）をランダムで１枚プレゼント！<br>
									         また、期間中“着物”でお越しの方には３種すべてをプレゼントします♪ぜひ着物でご来場ください。<br>
									         <br>
									         <p class="tokuten_pic"><img class="image" src="../news/img/20231227/tokuten_card.png"></p>
									         <br>
									         <ul class="memo">
													<li>特典はなくなり次第終了となります。</li>
													<li>特典の絵柄はお選びいただけません。</li>
													<li>画像はイメージです。実際とは異なる場合がございます。</li>
												</ul>
								         </dd>
								         
								         <dt>限定グッズ付き日時指定券/入場券について</dt>
								         <dd>
								         	<div class="wrap_ticket">
									         	<p class="ticket_type"><span>販売期間</span></p>
									         	<div class="group">
										         	2023年11月10日（金）12:00～2024年1月23日（火）16:30
									         	</div>
								         	</div>
								         	<div class="wrap_ticket">
									         	<p class="ticket_type"><span>料金</span></p>
									         	<div class="group">
										         	3,000円
									         	</div>
								         	</div>
								         	<div class="wrap_ticket">
									         	<p class="ticket_type"><span>限定グッズ</span></p>
									         	<div class="group">
										         	万年カレンダー
										         	<ul class="memo">
															<li>数に限りがございます。</li>
														</ul>
									         	</div>
									         	<p class="coming_soon"><img class="image" src="img/calendar.jpg"></p>
								         	</div>
								         	<div class="gray_bg">
													<ul class="memo">
														<li>料金はすべて税込み表記となります。</li>
														<li>日時指定券および入場券ともに、限定グッズ付き入場券の設定がございます。</li>
														<li>ローソンチケットでお求めのお客様は、会場にお越しになる前に、コンビニにて発券をしてください。</li>
														<li>会期中は、松屋銀座8階イベントスクエア展覧会チケット売り場でも取り扱いをいたします。</li>
														<li>「限定グッズ付き入場券」はコンビニのレジでの発券時、「入場券」とは別に「限定グッズ引換券」が発券されます。必ずお客様ご自身で「入場券」と「限定グッズ引換券」があることをご確認下さい。後日、お申し出いただいても、コンビニでの再発券はいたしかねます。また引換券が無い場合は限定グッズのお渡しはできません。</li>
														<li>限定グッズのお引き換えは、会期中、企画展会場（入り口）のみとなります。</li>
														<li>グッズは会期中、購入されたチケットの枚数分を会場（入り口）にてお引き替えします。</li>
													</ul>
												</div>
								         </dd>
								      </dl>
									</div>
							   </div>
						   </div>
						</div>
				   </div><?php /*?>primary<?php */?>
				</div><?php /*?>tab-contents-item<?php */?>
				
				<div class="tab-contents-item"><?php /*?>大阪<?php */?>
					<div class="primary">
						<div class="page_character lh-none">
							<img class="image" src="<?php echo $settings['rootdir']?>/img/common/mini_kiyoka2.png">
						</div>
						<div class="frame">
							<h2 class="tab_ttl">ご購入について</h2>
						   <div class="contents_box">
							   <div class="text">
								   <div class="table_layout">
									   <dl class="dl_tbl dl_tbl_large">
								         <dt>チケットの種類と料金</dt>
								         <dd>
								         	<table>
													<tbody>
														<tr>
															<td class="heading"></td>
															<td class="heading">対象期間</td>
															<td class="heading">一般</td>
															<td class="heading">ペア</td>
															<td class="heading">限定グッズ付き<br>（一般のみ）</td>
														</tr>
														<tr>
															<td class="heading">前売券</td>
															<td>
																2024年3月1日（金）<br>
																12:00～4月12日（金）<br>
																23:59
															</td>
															<td class="price">1,000<br class="sp">円</td>
															<td class="price">1,200<br class="sp">円</td>
															<td class="price">2,700<br class="sp">円</td>
														</tr>
														<tr>
															<td class="heading">当日</td>
															<td>
																2024年4月13日（土）0:00以降の会期中
															</td>
															<td class="price">1,200<br class="sp">円</td>
															<td class="price">1,400<br class="sp">円</td>
															<td class="price">2,900<br class="sp">円</td>
														</tr>
													</tbody>
												</table>
												<div class="gray_bg">
													<ul class="memo">
														<li>料金はすべて税込み表記となります。</li>
														<li>ペア券1枚で「2名」入場できます。２名同時にご入場ください。</li>
														<li>未就学児無料</li>
														<li>前売券の販売は、ローソンチケットのみでの取り扱いとなります。</li>
													</ul>
												</div>
								         </dd>
								         
								         <dt>チケット販売スケジュール</dt>
								         <dd>
								        		<div class="wrap_ticket">
									         	<p class="ticket_type"><span>入場券/限定グッズ付き入場券</span></p>
									         	
									         	<table class="ticket_schedule">
														<tbody>
															<tr>
																<th class="ttl">販売開始</th>
																<td>2024年3月1日（金）12:00～5月6日（月・振）17:30</td>
															</tr>
														</tbody>
													</table>
												</div>
			
										      <div class="btns">
											      <a class="btn" href="https://l-tike.com/watakon_ten/" target="_blank" rel="noopener noreferrer">購入はこちらから</a>
										      </div>
								         </dd>
								         
								         <dt>チケット販売方法</dt>
								         <dd class="border_btn_none">
								         	<div class="wrap_ticket">
									         	<p class="ticket_type"><span>前売券および日時指定券の販売</span></p>
									         	前売券の販売は、ローソンチケットのみでのお取り扱いとなります。<br>
													・<span class="link">
														<a href="https://l-tike.com/watakon_ten/" target="_blank">
															インターネット予約
														</a><br>
													・全国ローソン・ミニストップ設置のLoppi　ローソンチケット（Ｌコード54292）<br>
													・<span class="link"><a href="https://l-tike.com/contact/" target="_blank">チケットに関するお問い合わせ</a></span>

								         	</div>
									         	<div class="gray_bg">
														<ul class="memo">
															<li class="bold">ローソンチケットでのインターネット予約のご利用にはチケット代の他に手数料が必要です。</li>
															<li>会期中は４階レジカウンターで当日入場券の販売をいたします。</li>
															<li>グッズ付入場券の商品は会期中、会場受付にてお引き換えいたします。</li>
														</ul>
													</div>
								         	</div>
								         </dd>
								      </dl>
									</div>
							   </div>
						   </div>
						</div>
						
						<div class="frame guide tab_guide goods">
							<h2>入場者特典について</h2>
						   <div class="contents_box">
							   <div class="text">
								   <div class="table_layout">
									   企画展にご来場いただいた方に、展示会場入り口にて特製ステッカー（全６種）をランダムで１枚プレゼント！<br>
									   会期の前半と後半で絵柄が異なります。<br>
									   <br>
									   <dl class="dl_tbl dl_tbl_large">
								         <dt>4/13（土）～24（水）：美世、清霞、香耶、幸次</dt>
								         <dd>
								         	<p><img src="img/sticker1.jpg" style="width: 100%;"></p>
								         </dd>
								         <dt>4/25（木）～5/6（月）：美世、清霞、五道、新</dt>
								         <dd>
								         	<p><img src="img/sticker2.jpg" style="width: 100%;"></p>
								         </dd>
								         <dd>
								         	<div class="gray_bg">
													<ul class="memo">
														<li>特典はなくなり次第終了となります。</li>
														<li>特典の絵柄はお選びいただけません。</li>
														<li>画像はイメージです。実際とは異なる場合がございます。</li>
													</ul>
												</div>
								         </dd>
								      </dl>
									</div>
							   </div>
						   </div>
						</div>
						
						<div class="frame guide tab_guide">
							<h2>限定グッズ付き入場券について</h2>
						   <div class="contents_box">
							   <div class="text">
								   <div class="table_layout">
									   <dl class="dl_tbl dl_tbl_large">
								         <dt>限定グッズ付き入場券について</dt>
								         <dd>
								         	<div class="wrap_ticket">
									         	<p class="ticket_type"><span>販売期間</span></p>
									         	<div class="group">
										         	2024年3月1日（金）12:00～5月6日（月・振）17:30
									         	</div>
								         	</div>
								         	<div class="wrap_ticket">
									         	<p class="ticket_type"><span>料金</span></p>
									         	<div class="group">
										         	2,900円（2,700円）
										         	<ul class="memo">
											         	<li>（　）内は前売り料金となります。</li>
										         	</ul>
									         	</div>
								         	</div>
								         	<div class="wrap_ticket">
									         	<p class="ticket_type"><span>限定グッズ</span></p>
									         	<div class="group">
										         	万年カレンダー
										         	<ul class="memo">
															<li>ローソンチケットにて取り扱い。</li>
															<li>会期中は、4階 イベントスペースチケット売り場でも取り扱いをいたします。</li>
															<li>数に限りがございます。</li>
														</ul>
									         	</div>
									         	<p class="coming_soon"><img class="image" src="img/calendar.jpg"></p>
								         	</div>
								         	<div class="gray_bg">
													<ul class="memo">
														<li>料金はすべて税込み表記となります。</li>
														<li>ローソンチケットでお求めのお客様は、会場にお越しになる前に、コンビニにて発券をしてください。</li>
														<li>「限定グッズ付き入場券」はコンビニのレジでの発券時、「入場券」とは別に「限定グッズ引換券」が発券されます。必ずお客様ご自身で「入場券」と「限定グッズ引換券」があることをご確認下さい。後日、コンビニでの再発券はいたしかねます。また引換券が無い場合は限定グッズのお渡しはできません。</li>
														<li>限定グッズのお引き換えは、会期中、企画展会場（入り口）のみとなります。</li>
														<li>グッズは会期中、購入されたチケットの枚数分を会場（入り口）にてお引き替えします。</li>
													</ul>
												</div>
								         </dd>
								      </dl>
									</div>
							   </div>
						   </div>
						</div>
				   </div><?php /*?>primary<?php */?>
				</div><?php /*?>tab-contents-item 大阪会場<?php */?>
				
				<div class="tab-contents-item"><?php /*?>福岡<?php */?>
					<div class="primary">
						<div class="page_character lh-none">
							<img class="image" src="<?php echo $settings['rootdir']?>/img/common/mini_kiyoka2.png">
						</div>
						<div class="frame">
						   <div class="contents_box">
							   <div class="text">
								   <div class="coming_soon">
									   <span>coming soon</span>
									</div>
							   </div>
						   </div>
						</div>
				   </div><?php /*?>primary<?php */?>
				</div><?php /*?>tab-contents-item 福岡会場<?php */?>
				
			</div>
      </div>
		
		
	</div><?php /*?>page_wrap wrap_contents<?php */?>
</div><?php /*?>wrap_contents_inner<?php */?>

<script>
	// タブ
	const tabList = document.querySelectorAll('.tab-list-item');
	// タブコンテンツ
	const tabContent = document.querySelectorAll('.tab-contents-item');
	
	//DOMが読み込み終わったら
	document.addEventListener('DOMContentLoaded', function(){
	  // タブに対してクリックイベントを適用
	  for(let i = 0; i < tabList.length; i++) {
	    tabList[i].addEventListener('click', tabSwitch);
	  }
	  // タブをクリックすると実行する関数
	  function tabSwitch(){
	    // activeクラスを削除
	    document.querySelectorAll('.active')[0].classList.remove('active');
	    // クリックしたタブにactiveクラスを付与    
	    this.classList.add('active');
	    // showクラスを削除
	    document.querySelectorAll('.show')[0].classList.remove('show');
	    // タブを配列風オブジェクトとして定義
	    const aryTabs = Array.prototype.slice.call(tabList);
	    // クリックしたタブの配列番号を取得     
	    const index = aryTabs.indexOf(this);
	    // クリックしたタブと同じ配列番号のタブコンテンツにshowクラスを付与    
	    tabContent[index].classList.add('show');
	  };
	});
</script>
<?php include_once("{$settings['docroot']}/inc/footer.inc"); ?>

