<?php

$title = "$page_ttl | ";
$page = "features";
require_once("../common.php");
include_once("{$settings['docroot']}/inc/meta.inc");
include_once("{$settings['docroot']}/inc/header.inc");

?>

<div id="<?php echo $page?>" class="page_wrap wrap_contents">
	<?php include_once("../inc/sakura.inc"); ?>
	<div class="wrap_contents_inner">
		<div class="page_ttl page">
         <div class="wrap_page_ttl">
            <h1>
				   <p><img class="image" src="../img/common/musubi_purple.png"></p>
				   <?php echo $page_ttl?>
				</h1>
         </div>
      </div>
		
		<div class="primary">
			<div class="page_character lh-none">
				<img class="image" src="<?php echo $settings['rootdir']?>/img/common/mini_kaya2.png">
			</div>
			<div class="frame">
				<h2>見どころ詳細</h2>
			   <div class="contents_box">
				   <div class="text">
					   
					   <p><img class="image" src="img/map.jpg"></p>
					   <br><br>
					   <dl class="d_reset">
						   <dt class="d">
						   	<span><img class="image ttl_sakura_before" src="../img/common/ttl_hanabira.svg">お出迎え</span>
						   </dt>
						   <dd class="sub_ttl"><span>心ときめく録り下ろしボイス</span></dd>
						   <dd>
						   	斎森美世（CV.上田麗奈）と久堂清霞（CV.石川界人）による、企画展録り下ろしボイスでお出迎え。本企画展の物語のはじまりを体感していただきます。
						   	<p class="cut_image"><img class="image" src="img/01_story.jpg"></p>
						   	<p class="memo">撮影：鈴木康道</p>
						   </dd>
						   
						   <dt class="d">
						   	<span><img class="image ttl_sakura_before" src="../img/common/ttl_hanabira.svg">二人のときめき</span>
						   </dt>
						   <dd class="sub_ttl"><span>久堂清霞の書斎</span></dd>
						   <dd>
						   	二人の出会いの場である「久堂清霞の書斎」を再現。<br>
書斎のガラス戸の外には、時間によって移り変わる景色や、第一話「出会い」の本編映像が投影されます。大阪会場からは、新規録り下ろしボイスも追加予定です。「綺麗な人・・・」 と、美世の心が動いたあの瞬間をご堪能ください。
								<p class="cut_image"><img class="image" src="img/02_encounter1.jpg"></p>
						   	<br>
						   </dd>
						   <dd class="sub_ttl"><span>映像展示、櫛・組み紐の実物展示</span></dd>
						   <dd>
						   	第二話「旦那さまという御方」朝食シーンの映像展示、お互いに贈りあった、櫛、組み紐の実物展示をお楽しみいただきます。
						   	<div class="cut_image_2col">
							   	<p><img class="image" src="img/03_excited1.jpg"></p>
							   	<p><img class="image" src="img/03_excited2.jpg"></p>
						   	</div>
						   	<br>
						   </dd>
						   <dd class="sub_ttl"><span>音声体験</span></dd>
						   <dd>
						   	第四話「おくりもの」にて、美世が清霞に組み紐を贈るシーンの音声体験をお楽しみいただきます。
						   	<p class="cut_image"><img class="image" src="img/03_excited3.jpg"></p>
						   </dd>
						   
						   <dt class="d">
						   	<span><img class="image ttl_sakura_before" src="../img/common/ttl_hanabira.svg">決意と追憶</span>
						   </dt>
						   <dd>
						   	<br>
						   	「斎森家の蔵」をイメージしたエリア。<br>
第六話「決意と雷鳴」の世界観を、“ことば”に注目して体感いただくほか、第七話「夏の華の淑女」から第十一話「母が遺したもの」までの名場面の数々を場面写真で振り返ります。
						   	<div class="cut_image_2col">
							   	<p><img class="image" src="img/04_determination1.jpg"></p>
							   	<p><img class="image" src="img/04_determination2.jpg"></p>
						   	</div>
						   </dd>
						   
						   <dt class="d">
						   	<span><img class="image ttl_sakura_before" src="../img/common/ttl_hanabira.svg">幸せ</span>
						   </dt>
						   <dd class="sub_ttl"><span>第十二話「暗闇の中の光」映像体験</span></dd>
						   <dd>
						   	第十二話「暗闇の中の光」のダイジェスト映像を、大型スクリーンで体感。<br>
						   	映像に連動した照明演出で、あの感動のシーンをお楽しみいただきます。
						   	<p class="cut_image"><img class="image" src="img/05_impressed1.jpg"></p>
						   </dd>
						   
						   <dt class="d">
						   	<span><img class="image ttl_sakura_before" src="../img/common/ttl_hanabira.svg">広がる世界</span>
						   </dt>
						   <dd class="sub_ttl"><span>舞台衣裳展示</span></dd>
						   <dd>
						   	2023年8月に実施された「<a href="https://www.watakon-stage.net/" target="_blank" rel="noopener noreferrer">舞台『わたしの幸せな結婚』－帝都陸軍オクツキ奇譚－</a>」で使用された「久堂清霞」「五道佳斗」「鶴木新」の衣裳を展示します。
						   	<p class="cut_image"><img class="image" src="img/09_stage.jpg"></p>
						   	<p class="memo">
							   	&copy;舞台「わたしの幸せな結婚」製作委員会<br>
							   	※写真は過去の催事の様子です。一部展示に変更がございます。
							   </p>
						   	<br>
						   </dd>
						   <dd class="sub_ttl"><span>制作陣こだわりシーン展示</span></dd>
						   <dd>
						   	制作陣の“心ときめく”シーンの原画＆コメント展示。<br>
						   	どんなシーンが飾られるかお楽しみに！
						   	<div class="cut_image">
						   		<p><img class="image" src="img/07_director_impressed.jpg"></p>
						   	</div>
						   	<br>
						   </dd>
						   <dd class="sub_ttl"><span>原作・コミカライズ展示</span></dd>
						   <dd>
						   	企画展に寄せて描いていただいた原作・コミカライズの先生方の色紙とメッセージ展示、アニメ声優キャスト陣の色紙展示など、豪華展示が盛りだくさん。
						   	<div class="cut_image">
							   	<p><img class="image" src="img/08_book.jpg"></p>
						   	</div>
						   	<br>
						   </dd>
						   <dd class="sub_ttl"><span>桜のフォトスポット＆メッセージコーナー</span></dd>
						   <dd>
						   	メッセージ付箋を貼り付けられる“桜のフォトスポット” で企画展の物語を締めくくります。本企画展の感想を桜の付箋に記して、幻想的な空間の中で満開の桜を咲かせてください！
						   	<div class="cut_image">
							   	<p><img class="image" src="img/06_shidare_sakura.jpg"></p>
						   	</div>
						   </dd>
						   <dd>
						   	<ul class="memo" style="text-align: left; margin-top: 4em !important;">
								   <li>写真は東京会場の様子です。</li>
								   <li>各巡回会場では、展示内容が異なる場合がございます。</li>
							   </ul>
						   </dd>
					   </dl>
					   
				   </div>
			   </div>
			</div>
	   </div>
		
	</div><?php /*?>page_wrap wrap_contents<?php */?>
</div><?php /*?>wrap_contents_inner<?php */?>

<?php include_once("{$settings['docroot']}/inc/footer.inc"); ?>
